'use strict';
(() => {
  const G=window.Game,U=G.UI,$=id=>document.getElementById(id);
  U.archive=(tab='history')=>{
    U.show('모험가의 기록장','<nav class="menu-tabs" aria-label="기록 분류"></nav><div class="archive-list"></div>',[{text:'원정 메뉴',run:U.runDashboard},{text:'닫기',run:U.close}],true);
    const nav=$('modal-body').querySelector('nav'),list=$('modal-body').querySelector('.archive-list');
    for(const [id,title]of [['history','원정 기록'],['codex','수집 도감']]){const b=document.createElement('button');b.textContent=title;b.setAttribute('aria-pressed',String(tab===id));b.onclick=()=>U.archive(id);nav.append(b);}
    const add=(title,detail)=>{const row=document.createElement('article');row.className='record-row';const h=document.createElement('strong'),p=document.createElement('p');h.textContent=title;p.textContent=U.displayText(detail);row.append(h,p);list.append(row);};
    if(tab==='history'){const records=G.history();if(!records.length)add('아직 원정 기록이 없어요','첫 원정을 시작해 자신만의 이야기를 남겨보세요.');for(const r of records){add(`${r.completed?'정복':'도전'} · ${r.stage}/40 · ${G.jobs[r.job]?.name||r.job}`,`${r.daily?'오늘의 원정 · ':''}${Math.floor(r.elapsedSeconds/60)}분 · ${r.cause||'완료'} · 시드 ${r.seed} · ${r.at||''}`);add('이번 원정의 성장',`전투 방식: ${(r.builds||[]).map(id=>G.buildCatalog[id]?.name||id).join(', ')} · 유물: ${(r.relics||[]).map(id=>G.relicCatalog[id]?.name||id).join(', ')||'없음'} · 얻은 장비: ${(r.gearGained||[]).map(id=>G.items[id]?.name||id).join(', ')||'없음'}`);add('선택한 길과 이야기',(r.choices||[]).map(c=>`${c.stage}단계 ${c.type}`).concat((r.events||[]).map(e=>`${e.stage}단계 ${e.result||e.choice}`)).join(' → ')||'선택 기록 없음');}}
    else{const c=G.codex();add('발견의 발자취',`최고 ${c.best||0}단계 · 해금 ${c.unlocks.join(', ')||'첫 원정으로 새로운 선택을 발견하세요'}`);for(const [kind,items]of [['장비',c.items],['유물',c.relics]])for(const item of items)add(`${kind} · ${item.seen?item.name:'아직 발견하지 못한 항목'}`,item.seen?(G.items[item.id]?.description||G.relicCatalog?.[item.id]?.description||'수집 완료'):'원정에서 발견하면 이름과 효과가 기록됩니다.');}
  };
  U.settings=()=>{
    U.show('소리와 화면 설정','<div class="settings-list"></div><div class="save-transfer"><strong>모험을 다른 기기로</strong><p>저장 파일에는 현재 원정과 장비, 기록이 포함됩니다.</p><button id="export-save">저장 파일 내보내기</button><label class="file-label" for="import-save">저장 파일 가져오기<input id="import-save" type="file" accept=".json,application/json"></label><p id="transfer-status" role="status"></p></div>',[{text:'닫기',primary:true,run:U.close}],true);
    const list=$('modal-body').querySelector('.settings-list');
    for(const [key,title]of [['sfx','효과음'],['bgm','배경 음악 · 오리지널 숲의 멜로디'],['reducedMotion','움직임 줄이기']]){const label=document.createElement('label');label.className='setting-row';const input=document.createElement('input');input.type='checkbox';input.checked=G.settings[key];input.onchange=()=>{G.settings[key]=input.checked;G.applySettings();G.save();if(key==='sfx')G.beep(520);};label.append(input,document.createTextNode(title));list.append(label);}
    const label=document.createElement('label');label.className='setting-row';label.textContent='시각 효과 강도 ';const select=document.createElement('select');select.setAttribute('aria-label','시각 효과 강도');for(const [value,title]of [['off','끄기'],['low','약하게'],['full','전체']]){const option=document.createElement('option');option.value=value;option.textContent=title;select.append(option);}select.value=G.settings.intensity;select.onchange=()=>{G.settings.intensity=select.value;G.save();};label.append(select);list.append(label);
    const fullscreen=document.createElement('button');fullscreen.id='fullscreen-toggle';fullscreen.textContent=document.fullscreenElement?'전체화면 나가기':'전체화면으로 보기';fullscreen.disabled=!document.fullscreenEnabled;const fullscreenStatus=document.createElement('p');fullscreenStatus.id='fullscreen-status';fullscreenStatus.setAttribute('role','status');fullscreenStatus.textContent=document.fullscreenEnabled?'선택 사항입니다. 일반 화면에서도 모든 조작을 사용할 수 있어요.':'이 브라우저는 전체화면을 지원하지 않습니다. 일반 화면으로 플레이하세요.';list.append(fullscreen,fullscreenStatus);
    fullscreen.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();fullscreen.textContent=document.fullscreenElement?'전체화면 나가기':'전체화면으로 보기';fullscreenStatus.textContent='화면 크기를 변경했습니다. 닫기를 눌러 모험을 이어가세요.';}catch{fullscreenStatus.textContent='전체화면을 열지 못했습니다. 일반 화면으로 계속 플레이할 수 있어요.';}};
    $('export-save').onclick=()=>{const blob=new Blob([G.exportSave()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='maple-forest-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('transfer-status').textContent='저장 파일을 내려받았습니다.';};
    $('import-save').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2000000){$('transfer-status').textContent='파일이 너무 큽니다. 2MB 이하 저장 파일을 선택하세요.';return;}const result=G.importSave(await file.text());$('transfer-status').textContent=result.ok?'저장 파일을 가져왔습니다. 닫은 뒤 모험을 이어가세요.':`가져오기 실패: ${result.error}`;if(result.ok){G.applySettings();G.refresh();}};
  };
  const inventory=U.inventory;let sort='name',selected='';
  U.inventory=()=>{const same=$('modal').open&&$('modal-title').textContent==='모험가의 가방';const scroll=same?$('modal-body').scrollTop:0;inventory();const list=$('modal-body').querySelector('.inventory-list');list.replaceChildren();const toolbar=document.createElement('label');toolbar.className='bag-toolbar';toolbar.textContent=`재료 ${G.p.materials||0}개 · 정렬 `;const select=document.createElement('select');select.setAttribute('aria-label','장비 정렬');for(const [value,title]of [['name','이름'],['power','성능'],['slot','종류']]){const option=document.createElement('option');option.value=value;option.textContent=title;select.append(option);}select.value=sort;select.onchange=()=>{sort=select.value;U.inventory();};toolbar.append(select);list.before(toolbar);
    const ids=[...G.p.inventory].filter(id=>G.items[id]).sort((a,b)=>{const x=G.items[a],y=G.items[b];return sort==='power'?((y.attack||0)+(y.defense||0))-((x.attack||0)+(x.defense||0)):sort==='slot'?x.slot.localeCompare(y.slot):x.name.localeCompare(y.name,'ko');});
    for(const id of ids){const item=G.items[id],equipped=G.p.equipment[item.slot]===id,current=G.items[G.p.equipment[item.slot]],base=!G.compareItem(id).canSell;const row=document.createElement('article');row.className='item-row';row.dataset.item=id;row.dataset.selected=String(selected===id);const text=document.createElement('div'),h=document.createElement('strong'),p=document.createElement('small'),comparison=document.createElement('small');h.textContent=item.name;p.textContent=item.description||`${item.rarity} · ${item.slot==='weapon'?'무기':'방어구'}`;const delta=(item.attack||item.defense||0)-(current?.attack||current?.defense||0);comparison.textContent=`현재 장비 대비 ${item.slot==='weapon'?'공격력':'방어력'} ${delta>=0?'+':''}${delta} · ${(item.tags||[]).map(U.displayText).join(' / ')}`;text.append(h,p,comparison);const actions=document.createElement('div');actions.className='item-actions';for(const [title,fn,disabled]of [[equipped?'장착 중':'장착',()=>G.equip(id),equipped||(item.job!=='all'&&item.job!==G.p.job)],['판매',()=>G.sell(id),equipped||base],['분해',()=>G.dismantle(id),equipped||base]]){const b=document.createElement('button');b.textContent=title;if(title==='판매'||title==='분해'){b.className='destructive';const value=document.createElement('small');value.textContent=title==='판매'?`+${item.sell} 골드`:`+${G.compareItem(id).materials} 재료`;b.append(value);}b.disabled=disabled;b.setAttribute('aria-label',`${item.name} ${title}`);b.onclick=()=>{selected=id;if(fn()){G.save();U.inventory();}};actions.append(b);}row.append(text,actions);list.append(row);}
    $('modal-body').scrollTop=scroll;
  };
  $('inventory').onclick=()=>U.inventory();$('sound').onclick=U.settings;$('sound').textContent='설정';$('sound').setAttribute('aria-label','소리 화면 저장 설정');$('sound').removeAttribute('aria-pressed');
  const refresh=G.refresh;G.refresh=()=>{refresh();$('mobile-dodge').textContent=G.p.dodgeCooldown>0?`회피 ${G.p.dodgeCooldown.toFixed(1)}초`:'회피 준비';};
  document.addEventListener('fullscreenchange',()=>{const b=$('fullscreen-toggle');if(b)b.textContent=document.fullscreenElement?'전체화면 나가기':'전체화면으로 보기';});
  G.applySettings();
})();
