'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const output=process.env.ARTIFACT_DIR||'.omo/mobile-qa',base=process.env.BASE_URL||'http://127.0.0.1:8765';
fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome'});const results=[],errors=[];const record=(name,detail={})=>{results.push({name,ok:true,...detail});console.log('PASS '+name);};try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,deviceScaleFactor:2});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#expedition-start').tap();await page.getByRole('button',{name:'새 원정 시작',exact:true}).tap();await page.locator('.job-card.warrior').tap();await page.locator('.reward-card').first().tap();
 const cdp=await context.newCDPSession(page);const point=async(selector,id)=>{const b=await page.locator(selector).boundingBox();assert(b);return{x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2),id,radiusX:4,radiusY:4};};
 const right=await point('[data-hold=right]',1),attack=await point('.touch-controls [data-action=attack]',2),jump=await point('.touch-controls [data-action=jump]',3);
 const before=await page.evaluate(()=>Game.p.x);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right,attack]});await page.waitForTimeout(300);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right,attack,jump]});await page.waitForTimeout(180);const moving=await page.evaluate(()=>({x:Game.p.x,y:Game.p.y,keys:[...Game.keys]}));assert(moving.x>before+30);assert(moving.y<610);assert(moving.keys.includes('attack'));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(80);assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);record('real three-finger movement attack jump + release',moving);
 await page.locator('.touch-controls [data-action=dodge]').tap();assert(await page.evaluate(()=>Game.p.dodgeCooldown>0));record('touch dodge feedback');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right]});await page.waitForTimeout(120);await page.locator('#mobile-menu').tap();const paused=await page.evaluate(()=>({t:Game.p.run.elapsedSeconds,keys:[...Game.keys],paused:Game.paused}));assert(paused.paused);assert.deepEqual(paused.keys,[]);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>Game.p.run.elapsedSeconds),paused.t);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.getByRole('button',{name:'게임으로 돌아가기',exact:true}).tap();assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);record('menu clears held touch and pauses objective timer');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);record('real touch cancellation');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...right,x:right.x+100,y:right.y-60}]});assert((await page.evaluate(()=>[...Game.keys])).includes('right'));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);record('pointer capture holds outside button then releases');
 const seed=await page.evaluate(()=>Game.p.run.seed);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right]});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(200);assert(await page.evaluate(()=>Game.paused));assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);assert.equal(await page.evaluate(()=>Game.p.run.seed),seed);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('#close-modal').tap();record('orientation preserves expedition and safely pauses');
 for(const viewport of [{width:360,height:800},{width:390,height:844},{width:844,height:390},{width:1280,height:900}]){await page.setViewportSize(viewport);await page.waitForTimeout(150);if(await page.locator('#modal').isVisible())await page.locator('#close-modal').click();const dims=await page.evaluate(()=>({height:document.documentElement.scrollHeight,width:document.documentElement.scrollWidth,view:Game.viewHeight,canvas:Game.width,cssHeight:document.querySelector('#game').getBoundingClientRect().height,keys:[...document.querySelectorAll('.touch-controls button')].map(b=>{const r=b.getBoundingClientRect();return{w:r.width,h:r.height,top:r.top,bottom:r.bottom};})}));assert(dims.width<=viewport.width);if(viewport.width<=1000){assert(dims.height<=viewport.height+1);for(const b of dims.keys){assert(b.w>=44&&b.h>=44&&b.bottom<=viewport.height+1&&b.top>=0);}}await page.screenshot({path:path.join(output,`mobile-${viewport.width}-battle.png`)});record('viewport '+viewport.width,{...dims,spriteCss:54*dims.cssHeight/dims.view});}
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150);if(await page.locator('#modal').isVisible())await page.locator('#close-modal').tap();await page.locator('#mobile-menu').tap();await page.getByRole('button',{name:'설정 · 저장 파일',exact:true}).tap();const download=page.waitForEvent('download');await page.locator('#export-save').tap();await (await download).saveAs(path.join(output,'export.json'));const save=JSON.parse(fs.readFileSync(path.join(output,'export.json'),'utf8'));assert.equal(save.run.seed,seed);await page.locator('#import-save').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.getByText(/가져오기 실패/).waitFor();assert.equal(await page.evaluate(()=>Game.p.run.seed),seed);await page.locator('#import-save').setInputFiles(path.join(output,'export.json'));await page.getByText(/저장 파일을 가져왔습니다/).waitFor();await page.reload();assert.equal(await page.evaluate(()=>Game.p.run.seed),seed);await page.locator('#start').tap();record('UI export invalid import valid import and reload preserve run');
 await page.keyboard.down('ArrowRight');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert(await page.evaluate(()=>Game.paused));assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);await page.keyboard.up('ArrowRight');record('synthetic blur lifecycle fixture clears keyboard input');
 await page.locator('#close-modal').tap();await page.keyboard.down('ArrowRight');await page.locator('#mobile-menu').tap();await page.getByRole('button',{name:'게임으로 돌아가기',exact:true}).tap();await page.evaluate(()=>document.getElementById('game').dispatchEvent(new KeyboardEvent('keydown',{code:'ArrowRight',repeat:true,bubbles:true})));assert.deepEqual(await page.evaluate(()=>[...Game.keys]),[]);await page.keyboard.up('ArrowRight');record('modeled OS key repeat cannot resume stale movement after menu');
 // The following fixtures prepare inventory/decision states; actions themselves use real touch UI.
 await page.evaluate(()=>{Game.p.inventory=['warrior-0','warrior-1','warrior-2','warrior-3','armor-0','armor-1','armor-2','archer-1'];Game.p.gold=300;Game.UI.inventory();});await page.getByLabel('장비 정렬').selectOption('power');await page.getByRole('button',{name:'수정 군주의 검 장착',exact:true}).tap();assert.equal(await page.evaluate(()=>Game.p.equipment.weapon),'warrior-3');assert.equal(await page.getByLabel('장비 정렬').inputValue(),'power');await page.getByRole('button',{name:'단풍 장검 판매',exact:true}).tap();assert(!(await page.evaluate(()=>Game.p.inventory)).includes('warrior-1'));await page.getByRole('button',{name:'단풍 가죽옷 분해',exact:true}).tap();assert(!(await page.evaluate(()=>Game.p.inventory)).includes('armor-1'));assert(await page.evaluate(()=>Game.p.materials>0));await page.screenshot({path:path.join(output,'mobile-bag.png')});record('fixture inventory real equip sell dismantle and sort retention');
 await page.evaluate(()=>{Game.p.run.phase='reward';Game.p.run.rewards=Game.makeRunRewards();Game.openRunUI();});const rewardCount=await page.locator('.reward-card').count();assert.equal(rewardCount,3);await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>Game.p.run.phase),'reward');await page.locator('#close-modal').tap();await page.locator('#expedition').tap();assert.equal(await page.locator('.reward-card').count(),3);record('fixture pending reward survives rotate close and reopen');
 const first=await point('.reward-card:first-child',9);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[first]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...first,y:Math.max(90,first.y-90)}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>Game.p.run.phase),'reward');record('real choice drag does not claim reward');await page.locator('.reward-card').first().tap();assert.equal(await page.evaluate(()=>Game.p.run.phase),'route');record('fixture reward single claim through touch');
 assert.deepEqual(errors,[]);record('no browser errors');fs.writeFileSync(path.join(output,'mobile-results.json'),JSON.stringify({results,errors},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
